#!/bin/bash

# Check if the input file is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <input_file>"
  exit 1
fi

# Get input file
input_file="$1"

# Get the basename without extension
input_basename="$(basename "${input_file%.*}")"

# Define output file
output_file="${input_basename}-compressed.mp4"

# Compress video using H.264 codec and resize resolution
ffmpeg -i "${input_file}" -c:v libx264 -preset slow -crf 23 -pix_fmt yuv420p "${output_file}"
