#!/bin/bash

# Check if the input file is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <input_tag>"
  exit 1
fi

# Get input tag
input_tag="$1"

adb shell screenrecord /sdcard/Movies/$input_tag-android.mp4
